# log配置文件

version: 1
disable_existing_loggers: False
formatters:  # 格式设置
        simple:
            format: "%(asctime)s [%(filename)s:%(lineno)d] [%(levelname)s]- %(message)s"
        standard:
            format: '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(levelname)s]- %(message)s'
handlers:  # handler设置，可以定义多个handler
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers: # logger设置， 可定义多个logger
    info:
            level: INFO
            handlers: [info_file_handler]
            propagate: no
    error:
            level: ERROR
            handlers: [error_file_handler]
            propagate: no
root:
    level: INFO
    loggers: [info,error]
    handlers: [console,info_file_handler,error_file_handler]